file_format: "1"
id: crosses
name: Crosses
type: shield
url: https://github.com/Good-Great-Grand-Wonderful/crosses
# pro_micro と nice_nano の両方をサポートする場合
requires: [pro_micro, nice_nano]
features:
  - keys
  - pointer
  - underglow
siblings:
  - crosses_left
  - crosses_right
